# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 029c30619ae8440c7b514a777a7415b4f2ea0747805ad9d68479b0ba95b40bcdb87344a6a0e22de18244ef84f0f7773702c6d464a582e242f53a36c0a89a5fbf

test:
  secret_key_base: def12afcda77a11234493c5b06e8980fc1b551b4b3e1e53284be77f9c4c8511646ce5499a25e1f8c891672c7f1021e863c80a200d2adea1cd25ed8b7df982279

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
